extends:
  - '@35up/35up-base'
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - tsconfig.json
    - tsconfig.test.json
overrides:
  -
    files:
      - "**/*.test.ts"
    rules:
      "@typescript-eslint/ban-ts-ignore": off
