branches:
  only:
    - master

language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

script:
  - make ci

notifications:
  slack:
    rooms:
      - caseable-it:jwDzQUtpgjOcN0PP8QaUhKZp
    on_success: change
    on_failure: always
