branches:
  only:
    - master

language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

install:
  - npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_NPM_TOKEN}"

script:
  - npm run ci

notifications:
  slack:
    rooms:
      - 35up:jwDzQUtpgjOcN0PP8QaUhKZp
    on_success: change
    on_failure: always
